// dLabPro class CFFTproc (FFTproc)
// - Header file
//
// AUTHOR : Matthias Eichner
// PACKAGE: dLabPro/classes
//
// This file was generated by dcg. DO NOT MODIFY! Modify fftproc.def instead.
// 
// Copyright 2013 dLabPro contributors and others (see COPYRIGHT file) 
// - Chair of System Theory and Speech Technology, TU Dresden
// - Chair of Communications Engineering, BTU Cottbus
// 
// This file is part of dLabPro.
// 
// dLabPro is free software: you can redistribute it and/or modify it under the
// terms of the GNU Lesser General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version.
// 
// dLabPro is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
// details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with dLabPro. If not, see <http://www.gnu.org/licenses/>.


//{{CGEN_INCLUDE
#include "dlp_config.h"
#include "dlp_object.h"
#include "dlp_fbaproc.h"
#include "dlp_data.h"
#include "dlp_math.h"
//}}CGEN_END

//{{CGEN_ERRORS
//}}CGEN_END

// C/C++ language abstraction layer
#undef fftproc_par
#define fftproc_par CFFTproc

// dLabPro/C++ language abstraction layer
#undef FFTproc
#define FFTproc CFFTproc

//{{CGEN_DEFINE
//}}CGEN_DEFINE

#ifndef __FFTPROC_H
#define __FFTPROC_H

//{{CGEN_HEADERCODE
//}}CGEN_HEADERCODE

// Class CFFTproc

class CFFTproc : public CFBAproc 
{

typedef CFBAproc inherited;
typedef CFFTproc thisclass;

//{{CGEN_FRIENDS
//}}CGEN_FRIENDS
public:
	CFFTproc(const char* lpInstanceName, BOOL bCallVirtual = 1);
	virtual ~CFFTproc();

// Virtual and static function overrides
public:
	virtual INT16 AutoRegisterWords();
	virtual INT16 Init(BOOL bCallVirtual = 0);
	virtual INT16 Reset(BOOL bResetMembers = 1);
	virtual INT16 Serialize(CDN3Stream* lpDest);
	virtual INT16 SerializeXml(CXmlStream* lpDest);
	virtual INT16 Deserialize(CDN3Stream* lpSrc);
	virtual INT16 DeserializeXml(CXmlStream* lpSrc);
	virtual INT16 Copy(CDlpObject* iSrc);
	virtual INT16 ClassProc();
	static  INT16 InstallProc(void* lpItp);
	static  CFFTproc* CreateInstance(const char* lpName);
	static  INT16 GetClassInfo(SWord* lpClassWord);
	virtual INT16 GetInstanceInfo(SWord* lpClassWord);
	virtual BOOL  IsKindOf(const char* lpClassName);
	virtual INT16 ResetAllOptions(BOOL bInit = 0);

// Primary method invocation functions            
// DO NOT CALL THESE FUNCTIONS FROM C SCOPE.      
// THEY MAY INTERFERE WITH THE INTERPRETER SESSION
#ifndef __NOITP
public:
//{{CGEN_PMIC
	INT16 OnAnalyze();
	INT16 OnWarp();
//}}CGEN_PMIC
#endif // #ifndef __NOITP

// Secondary method invocation functions
public:
//{{CGEN_SMIC
//}}CGEN_SMIC

// Option changed callback functions
public:
//{{CGEN_OCCF
	INT16 OnLmagSet();
	INT16 OnMagSet();
//}}CGEN_OCCF

// Field changed callback functions
public:
//{{CGEN_FCCF
	INT16 OnOrderChanged();
//}}CGEN_FCCF

// Scanned member functions
//{{CGEN_EXPORT

// Taken from 'fft_work.cpp'
	public: INT16 AnalyzeFrame();
	public: INT16 Warp(CData* dIn, CData* dOut, FLOAT64 nLambda, INT32 nDim);
	public: virtual void PrepareOutput(CData* dResult);
//}}CGEN_EXPORT

// Member variables
public:

//{{CGEN_FIELDS
	INT16            m_nOrder;
//}}CGEN_FIELDS

//{{CGEN_OPTIONS
	BOOL m_bLmag;
	BOOL m_bMag;
	BOOL m_bNse;
//}}CGEN_OPTIONS
}

;

// Scanned C (member) functions
//{{CGEN_CEXPORT

// Taken from 'fft_work.cpp'
//}}CGEN_CEXPORT

#endif //#ifndef __FFTPROC_H


// EOF
