## External library ipkclib
## - Makefile
##
## AUTHOR : F. Schiel (ipkclib), Matthias Wolff (Makefile)
## PACKAGE: dLabPro/ext
##
## LICENSE: ????

ifeq (${DLABPRO_HOME},)
  DLABPRO_HOME = ../..
endif

PROJNAME=ipkclib

CFLAGS_MSV += -D_DEBUG

## Target settings
SEXT    = c
SOURCES = phd
DEPS    = ipkclib.h

include $(DLABPRO_HOME)/make/ext.mk

## EOF
